# Render Backend Configuration for NexFlare

# Build Command
npm install && npm run build

# Start Command  
npm start

# Environment Variables (Add these in Render Dashboard)
NODE_ENV=production
PORT=10000
MONGODB_URI=mongodb+srv://arsathprabu996_db_user:Prabu1996@cluster0.4twhzfv.mongodb.net/nexflare?retryWrites=true&w=majority
JWT_SECRET=your-super-secure-jwt-secret-key-here
CORS_ORIGIN=https://nexflare-frontend.onrender.com

# Health Check
/api/health

# Auto-Deploy
✅ Enabled from GitHub
